# Generated by Django 3.1 on 2023-05-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20230510_1722'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonOneHanzi',
        ),
    ]
