# Generated by Django 3.1 on 2023-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0003_delete_lessononehanzi'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonOneHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Radical', models.CharField(max_length=1, null=True)),
            ],
        ),
    ]
