# Generated by Django 3.1 on 2023-05-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_lessononehanzi'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cName', models.CharField(max_length=20)),
                ('cSex', models.CharField(default='M', max_length=2)),
                ('cBirthday', models.DateField()),
                ('cEmail', models.EmailField(blank=True, default='', max_length=200)),
                ('cPhone', models.CharField(blank=True, default='', max_length=200)),
                ('cAddr', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
