# Generated by Django 3.1 on 2023-05-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonOneHanzi',
        ),
    ]
