# Generated by Django 3.1 on 2023-05-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20230510_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
