# Generated by Django 3.1 on 2023-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_lessononehanzi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdgradeF_LessonElevenHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonFiveHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonFourHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonNineHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonOneHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonSevenHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonSixHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonTenHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonThreeHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonTwelveHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdgradeF_LessonTwoHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=20)),
                ('Radical', models.CharField(max_length=1, null=True)),
                ('Total_strokes', models.IntegerField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='LessonOneHanzi',
            new_name='ThirdgradeF_LessonEightHanzi',
        ),
    ]
