# Generated by Django 3.1 on 2023-05-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20230511_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdgradef_lessoneighthanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonelevenhanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfivehanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfourhanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonninehanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessononehanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsevenhanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsixhanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontenhanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonthreehanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwelvehanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwohanzi',
            name='Total_strokes',
            field=models.IntegerField(),
        ),
    ]
