# Generated by Django 3.1 on 2023-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20230511_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='Hanzi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='Radical',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
