# Generated by Django 3.1 on 2023-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20230513_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdgradef_lessononehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=30),
        ),
    ]
