# Generated by Django 3.1 on 2023-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20230513_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdgradef_lessoneighthanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonelevenhanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfivehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfourhanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonninehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessononehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsevenhanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsixhanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontenhanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonthreehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwelvehanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwohanzi',
            name='Bopomofo',
            field=models.CharField(max_length=25),
        ),
    ]
