# Generated by Django 3.1 on 2023-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20230513_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdgradef_lessoneighthanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessoneighthanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonelevenhanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonelevenhanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfivehanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfivehanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfourhanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonfourhanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonninehanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonninehanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessononehanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessononehanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsevenhanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsevenhanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsixhanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonsixhanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontenhanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontenhanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonthreehanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessonthreehanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwelvehanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwelvehanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwohanzi',
            name='R_Bopomofo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thirdgradef_lessontwohanzi',
            name='Radical',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
