# Generated by Django 3.1 on 2023-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_thirdgrades_lessoneighthanzi_thirdgrades_lessonelevenhanzi_thirdgrades_lessonfivehanzi_thirdgrades_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thirdgrade_CourseHanzi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hanzi', models.CharField(max_length=1)),
                ('Bopomofo', models.CharField(max_length=25)),
                ('Radical', models.CharField(blank=True, max_length=1, null=True)),
                ('R_Bopomofo', models.CharField(blank=True, max_length=10, null=True)),
                ('Total_strokes', models.IntegerField()),
                ('cGrade', models.CharField(max_length=10)),
                ('cSemester', models.CharField(max_length=10)),
                ('cLesson', models.CharField(max_length=20)),
            ],
        ),
    ]
